// <auto-generated />
using System;
using Covid19HospitalManagement.EntityFrameworkDataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Covid19HospitalManagement.EntityFrameworkDataAccess.Migrations
{
    [DbContext(typeof(Covid19HospitalManagementContext))]
    [Migration("20200402235148_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Covid19HospitalManagement.Pocos.HospitalPoco", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("HospitalName")
                        .HasColumnName("Hospital_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SlotsAvailable")
                        .HasColumnName("Slots_Available")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Hospital");
                });

            modelBuilder.Entity("Covid19HospitalManagement.Pocos.PatientPoco", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("Hospital_ID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PatientName")
                        .HasColumnName("Patient_Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Hospital_ID");

                    b.ToTable("Patient");
                });

            modelBuilder.Entity("Covid19HospitalManagement.Pocos.PatientPoco", b =>
                {
                    b.HasOne("Covid19HospitalManagement.Pocos.HospitalPoco", "Hospital")
                        .WithMany("Patients")
                        .HasForeignKey("Hospital_ID");
                });
#pragma warning restore 612, 618
        }
    }
}
